### ISSUE TITLE
test failures on all builds of arkimet 1.26

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#228]
Since the main thing I changed compared to the previous (successful) builds has been moving the `make check` in the specfile in the `%check` section, I suppose this could be related to #218

Full logs:
https://travis-ci.org/github/ARPA-SIMC/arkimet/builds/693380036

Relevant bit:
```
======================================================================
ERROR: Check scanning COSMO nudging timeranges
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/arkimet-master/python/tests/test_scan_grib.py", line 333, in test_cosmo_nudging
    self.assertEqual(mds[0]["timerange"], "Timedef(0s, 254, 0s)")
KeyError: "section not found: 'timerange'"
-------------------- >> begin captured logging << --------------------
arkimet.scan.grib: ERROR: scanner function failed
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/arkimet-master/python/arkimet/scan/grib.py", line 31, in scan
    if scan(grib, md) is False:
  File "/root/rpmbuild/BUILD/arkimet-master/python/../arki/../conf/scan/grib2.py", line 21, in scan_grib2
    md["origin"] = {
TypeError: an integer is required (got type NoneType)
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: Check scanning of some Timedef cases
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/arkimet-master/python/tests/test_scan_grib.py", line 254, in test_ninfa
    self.assertEqual(mds[0]["timerange"], "Timedef(0s, 254, 0s)")
KeyError: "section not found: 'timerange'"
-------------------- >> begin captured logging << --------------------
arkimet.scan.grib: ERROR: scanner function failed
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/arkimet-master/python/arkimet/scan/grib.py", line 31, in scan
    if scan(grib, md) is False:
  File "/root/rpmbuild/BUILD/arkimet-master/python/../arki/../conf/scan/grib2.py", line 21, in scan_grib2
    md["origin"] = {
TypeError: an integer is required (got type NoneType)
--------------------- >> end captured logging << ---------------------
======================================================================
ERROR: Scan a GRIB2 with experimental UTM areas
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/arkimet-master/python/tests/test_scan_grib.py", line 269, in test_utm_areas
    self.assertEqual(mds[0]["origin"], "GRIB2(00200, 00000, 000, 000, 203)")
KeyError: "section not found: 'origin'"
-------------------- >> begin captured logging << --------------------
arkimet.scan.grib: ERROR: scanner function failed
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/arkimet-master/python/arkimet/scan/grib.py", line 31, in scan
    if scan(grib, md) is False:
  File "/root/rpmbuild/BUILD/arkimet-master/python/../arki/../conf/scan/grib2.py", line 21, in scan_grib2
    md["origin"] = {
TypeError: an integer is required (got type NoneType)
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
```

**Comment by spanezz** [comment]
In centos8 I don't see that failure, but i find instead:
```
COLUMNS=200 ./run-local help2man --include doc/mhooks-bufr-prepare --name='Read BUFR messages, and encode each subsection in a separate message' --section=1 --no-info --version-string="1.26" src/arki-bufr-prepare > arki-bufr-prepare.1 || rm -f arki-bufr-prepare.1
2098help2man: can't get `--help' info from src/arki-bufr-prepare
2099Try `--no-discard-stderr' if option outputs to stderr
```
and then:
```
install: cannot stat './arki-dump.1': No such file or directory
2103install: cannot stat './arki-query.1': No such file or directory
2104install: cannot stat './arki-check.1': No such file or directory
2105install: cannot stat './arki-mergeconf.1': No such file or directory
2106install: cannot stat './arki-scan.1': No such file or directory
2107install: cannot stat './arki-server.1': No such file or directory
2108install: cannot stat './arki-xargs.1': No such file or directory
2109install: cannot stat './arki-bufr-prepare.1': No such file or directory
2110make[2]: *** [Makefile:561: install-man1] Error 1
2111make[2]: Leaving directory '/root/rpmbuild/BUILD/arkimet-master'
```

**Comment by spanezz** [comment]
The bit you see, I see in fedora32, fedora31, fedora30. centos8 has the help2man problem. centos7 now has this one:
```
reftime-lex.cc: In function 'int yy_get_next_buffer(yyscan_t)':
1465reftime-lex.cc:1102:68: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
1466reftime-lex.cc:1680:3: note: in expansion of macro 'YY_INPUT'
```

**Comment by spanezz** [comment]
I found the problem with help2man, I'm now trying a build (ca2aecf3713489ac6ae5d0e4095c595d24c7ec44).

For the fedoras, I see the message `ECCODES ERROR   :  Unable to find template gridDefinitionSection from grib2/template.3.32768.def` in the build log which is exactly what I get if I try to run `grib_dump test/data/calmety_20110215.grib2` on a system without eccodes-simc.

I do see that eccodes-simc is getting installed in the CI. Could it be that eccodes-simc didn't install/hook correctly in the CI systems?

On the `trenta` test machine I can't reproduce this issue.

**Comment by brancomat** [comment]
Ok, it's a SPEC issue:
the mere presence of the eccodes-simc definitions is not enough, these environment variables needs to be set:
```
ECCODES_DEFINITION_PATH=/usr/share/eccodes-simc/definitions/:/usr/share/eccodes/definitions/
ECCODES_SAMPLES_PATH=/usr/share/eccodes-simc/samples/:/usr/share/eccodes/samples/
```
At the moment this happens only in the `%build` section (https://github.com/ARPA-SIMC/arkimet/blob/master/fedora/SPECS/arkimet.spec#L159), this should happen also in the `%check` section

**Comment by spanezz** [comment]
I pushed a fix for another issue I introduced in #206, cannot reproduce in my machine, but could reproduce in the test systems
